services:
  - type: web
    name: backend-InfoEvent_ticketing
    env: java
    plan: free
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: ADMIN_USERNAME
        value: ${ADMIN_USERNAME}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}