services:
  - type: web
    name: backend-InfoEvent_ticketing
    env: java
    plan: free
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-db-host:3306/your-db
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DB_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DB_PASS}